name: Deploy mysite App

on: 
  push: 
    branches: 
      - master # Trigger on push to master branch
#check
jobs: 
  build-and-deploy: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 # Set up Docker Buildx

      - name: Build with Maven
        run: mvn clean package

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image for multiple platforms
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 -t yuchankim/mysite:latest --push .
         
  SSH: 
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3

      - name: ssh to ec2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo mkdir -p /home/ec2-user/upload
            sudo docker pull yuchankim/api-phonelist:latest 
            sudo docker stop api-phonelist || true
            sudo docker rm api-phonelist || true
            sudo docker run -d \
              --name api-phonelist \
              -p 9000:9000 \
              -v /home/ec2-user/upload:/app/upload \
              yuchankim/api-phonelist:latest
